# Gradle
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.caching.debug=false
org.gradle.configureondemand=true
# Loom
fabric.loom.multiProjectOptimisation=true
# Mod Metadata
group=folk.sisby
user=sisby-folk
slug=euphonium
modId=euphonium
modName=Euphonium
modDescription=Ambient sounds suitable for vanilla minecraft
authors=svenhjol, Sisby folk
license=LGPL-3.0-or-later
# Mod Version
baseVersion=1.0.3
# Branch Metadata
branch=1.21.9
tagBranch=1.21.9
compatibleVersions=1.21, 1.21.9
compatibleLoaders=fabric, quilt, neoforge
